import jsPDF from "jspdf";
import { generateBuilderSchema, uploadArtifact } from "./aiSchema";
import type { BuilderResult, ReportSchema } from "./types";

/** Analytical report with KPI strip and simple SVG-style chart blocks rendered into PDF. */
export async function buildReport(topic: string, brief?: unknown): Promise<BuilderResult> {
  const schema = await generateBuilderSchema<ReportSchema>("report", topic, { brief });
  if (!schema) {
    return { title: topic, summary: "Report generation failed. Please try again." };
  }

  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const pw = pdf.internal.pageSize.getWidth();
  const ph = pdf.internal.pageSize.getHeight();
  const margin = 48;
  const cw = pw - margin * 2;

  // Cover.
  pdf.setFillColor(248, 250, 252);
  pdf.rect(0, 0, pw, ph, "F");
  pdf.setTextColor(15, 23, 42);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(30);
  pdf.text(pdf.splitTextToSize(schema.title, cw), margin, 140);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(100, 116, 139);
  pdf.text("Analytical Report  ·  Generated by Megsy", margin, 168);

  if (schema.executive_summary) {
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(12);
    const lines = pdf.splitTextToSize(schema.executive_summary, cw);
    pdf.text(lines, margin, 220);
  }

  // KPI strip on cover.
  if (schema.kpis?.length) {
    const cardW = (cw - 16 * (schema.kpis.length - 1)) / Math.max(1, schema.kpis.length);
    const yKpi = 360;
    schema.kpis.slice(0, 4).forEach((k, i) => {
      const x = margin + i * (cardW + 16);
      pdf.setFillColor(255, 255, 255);
      pdf.roundedRect(x, yKpi, cardW, 90, 12, 12, "F");
      pdf.setDrawColor(226, 232, 240);
      pdf.roundedRect(x, yKpi, cardW, 90, 12, 12, "S");
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      pdf.setTextColor(100, 116, 139);
      pdf.text(k.label, x + 14, yKpi + 22);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(20);
      pdf.setTextColor(15, 23, 42);
      pdf.text(String(k.value), x + 14, yKpi + 54);
      if (k.delta) {
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(10);
        pdf.setTextColor(34, 197, 94);
        pdf.text(k.delta, x + 14, yKpi + 74);
      }
    });
  }

  // Sections.
  for (const section of schema.sections || []) {
    pdf.addPage();
    pdf.setFillColor(255, 255, 255);
    pdf.rect(0, 0, pw, ph, "F");
    let y = margin;
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);
    pdf.setTextColor(15, 23, 42);
    pdf.text(pdf.splitTextToSize(section.heading, cw), margin, y);
    y += 32;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);
    pdf.setTextColor(30, 41, 59);
    const body = pdf.splitTextToSize(section.body, cw);
    for (const line of body) {
      if (y > ph - margin - 200) break; // leave room for chart
      pdf.text(line, margin, y);
      y += 16;
    }
    // Inline chart.
    if (section.chart?.data?.length) {
      y += 18;
      drawChart(pdf, margin, y, cw, 200, section.chart);
    }
  }

  const blob = pdf.output("blob");
  const safe = (schema.title || "report").replace(/[^a-z0-9-_ ]/gi, "_").slice(0, 50);
  const url = await uploadArtifact(blob, `${safe}.pdf`);

  return {
    title: schema.title,
    summary: `Your report "${schema.title}" is ready (${schema.sections?.length ?? 0} sections, ${schema.kpis?.length ?? 0} KPIs).`,
    downloadUrl: url ?? undefined,
    mimeType: "application/pdf",
  };
}

function drawChart(
  pdf: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  chart: NonNullable<ReportSchema["sections"]>[number]["chart"]
) {
  if (!chart) return;
  pdf.setDrawColor(226, 232, 240);
  pdf.setFillColor(248, 250, 252);
  pdf.roundedRect(x, y, w, h, 8, 8, "FD");
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  pdf.setTextColor(15, 23, 42);
  if (chart.title) pdf.text(chart.title, x + 14, y + 22);

  const data = chart.data || [];
  if (!data.length) return;
  const max = Math.max(...data.map(d => d.value), 1);
  const innerX = x + 14;
  const innerY = y + 36;
  const innerW = w - 28;
  const innerH = h - 56;

  if (chart.type === "pie") {
    // Simple legend list (jsPDF lacks easy pie chart math; draw colored squares + values).
    data.slice(0, 8).forEach((d, i) => {
      const ly = innerY + i * 18;
      pdf.setFillColor(99 + (i * 30) % 156, 102 + (i * 23) % 153, 241 - (i * 17) % 120);
      pdf.rect(innerX, ly, 10, 10, "F");
      pdf.setFontSize(10);
      pdf.setTextColor(30, 41, 59);
      pdf.text(`${d.name}  —  ${d.value}`, innerX + 18, ly + 9);
    });
    return;
  }

  // bar / line — use bars for both as a clean default.
  const barW = innerW / data.length - 8;
  data.forEach((d, i) => {
    const bx = innerX + i * (barW + 8);
    const bh = (d.value / max) * innerH;
    const by = innerY + innerH - bh;
    pdf.setFillColor(79, 70, 229);
    pdf.roundedRect(bx, by, barW, bh, 4, 4, "F");
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);
    const label = String(d.name).slice(0, 8);
    pdf.text(label, bx + barW / 2, innerY + innerH + 12, { align: "center" });
  });
}
